/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                           (c) Copyright 1992-2002, Jean J. Labrosse, Weston, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
*********************************************************************************************************
*/

#include    <reg52.h>

#include    <stdio.h>

#include    "os_cpu.h"
#include    "os_cfg.h"
#include    "ucos_ii.h"


